export const THROW_ERROR = 'THROW_ERROR'
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const TOPTRACKS_SUCCESS = 'TOPTRACKS_SUCCESS'
export const TOPARTISTS_SUCCESS= 'TOPARTISTS_SUCCESS'
export const REMOVE_TOKEN="REMOVE_TOKEN";